### PR TITLE
Fixed decimal places for lobby users

### PR DESCRIPTION
**Pull request by WebFreak001**
shows 5/6 instead of 5/6.0 or similar now. Players could have been annoyed by this.

### CODE REVIEW

**Review by tsbreuer — COMMENTED** [review]
I had already looked at this. Math.ceil is not required though, the number will always be an int, so you can just call ((int) round(X, 0)) and it would work.

**Comment by WebFreak001** [comment]
Math.ceil is needed to round up 5.25 to 6 as it would otherwise show 5/5 but not be done. If that custom round function rounds up, there is something wrong with the naming of that function.

**Comment by tsbreuer** [comment]
Ceil rounds to the next integer, round is to the nearest integer (up or down)

**Comment by WebFreak001** [comment]
Ceil is needed here because it would show 5/5 if the number was 5.25 with round. But the if only triggers if its above that number or equal to that number

**Comment by tsbreuer** [comment]
And it would trigger. The votestart / voteskip generally lack votes, so i'm totally fine with it being a bit lower.

**Comment by WebFreak001** [comment]
`if (ready / players >= 0.75)` imagine we have 7 players (`7*0.75 = 5.25` -> round = `5`, ceil = `6`):

with round:
Players 1 to 4 ready: `(1,2,3,4)/5 votes to start the game`
Player 5 ready: `if (5 / 8 >= 0.75) start()` -> `if (0.625 >= 0.75) start()` -> No start but instead this message: `5/5 votes to start the game` <- confusion in the lobby, "huh why doesn't it start? It says 5/5"
Player 6 ready: `6/8 have voted to start the game`

with Math.ceil:
Players 1 to 4 ready: `(1,2,3,4)/6 votes to start the game`
Player 5 ready: `5/6 votes to start the game`
Player 6 ready: `if (6 / 8 >= 0.75) start()` -> `if (0.75 >= 0.75) start()` -> Start and this message: `6/8 have voted to start the game`

**Comment by WebFreak001** [comment]
Also I looked at the code again and you are doing integer division here, not sure if java automatically converts that to a double because of the comparision `ready / players >= 0.75`, if there is no conversion to a double there it will only trigger once that is >=1 which means that it will only trigger if everyone is ready

**Comment by tsbreuer** [comment]
o shit i didnt want to reference this lol. Whatever.

**Pull request closed without merging**
